#=
 Various type aliases in the NewFrontend
=#

const Algorithm = NFAlgorithm
const ApplyFn = Function
const ApplyFunc = Function
const ComplexType = NFComplexType
const ComponentRef = NFComponentRef
const Connection = NFConnection
const Connections = NFConnections
const Connector = NFConnector
const ContainsPred = Function
const Dimension = NFDimension
const Equation = NFEquation
const EvalFunc = Function
const ExpandExp = NFExpandExp
const Expression = NFExpression
const ExpressionIterator = NFExpressionIterator
const FlatModel = NFFlatModel
const FoldFunc = Function
const FuncT = Function
const FuncType = Function
const FunctionDerivative = NFFunctionDerivative
const Import = NFImport
const MapExpFn = Function
const MapFn = Function
const MapFunc = Function
const OCConnectionGraph = NFOCConnectionGraph
const Operator = NFOperator
const PredFn = Function
const RangeIterator = NFRangeIterator
const Restriction = NFRestriction
const Sections = NFSections
const Statement = NFStatement
const Subscript = NFSubscript
# const Type = NFType 
const Variable = NFVariable
const VerifyModel = NFVerifyModel
const NFExpressionIterator = ExpressionIterator
#= Type defined by the compiler =#
const M_Type = NFType
