/* Simulation code for Influenza generated by the OpenModelica Compiler OpenModelica 1.16.0~dev-599-gbf1c298. */
#if !defined(Influenza__MODEL_H)
#define Influenza__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Influenza_functions.h"


extern void Influenza_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Influenza_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Influenza_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Influenza_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Influenza_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Influenza_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Influenza_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Influenza_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Influenza_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Influenza_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Influenza_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Influenza_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Influenza_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Influenza_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Influenza_relationDescription(int i);
extern void Influenza_function_initSample(DATA *data, threadData_t *threadData);
extern int Influenza_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Influenza_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Influenza_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Influenza_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Influenza_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Influenza_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Influenza_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Influenza_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Influenza_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Influenza_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Influenza_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Influenza_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Influenza_linear_model_frame(void);
extern const char* Influenza_linear_model_datarecovery_frame(void);
extern int Influenza_mayer(DATA* data, modelica_real** res, short *);
extern int Influenza_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Influenza_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Influenza_setInputData(DATA *data, const modelica_boolean file);
extern int Influenza_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Influenza_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Influenza_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int Influenza_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void Influenza_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Influenza_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Influenza_inputNames(DATA* data, char ** names);
extern int Influenza_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Influenza_functionLocalKnownVars(DATA*, threadData_t*);
extern int Influenza_symbolicInlineSystem(DATA*, threadData_t*);

#include "Influenza_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Influenza__MODEL_H) */


